---
title: "Publikationen"
page-layout: full
title-block-banner: true
---

# Publikationen aus dem Projekt

## Wissenschaftliche Publikationen

Ochsner, C., & Pampel, H. (2026). Ensuring the long-term
accessibility of scholarly blogs: Bloggers’ attitudes and practices. *Information Research an International Electronic Journal*, *31*(iConf), 1761–1769. <https://doi.org/10.47989/ir31iConf64176>

Ochsner, C., & Pampel, H. (2026). Eine Analyse infrastruktureller
Aspekte deutscher Wissenschaftsblogs. In S. Schwandt, G. Viehhauser, T.
Andrews, & T. Wallnig (Eds.), *Book of Abstracts—DHd 2026* (pp. 129–134). Zenodo. <https://doi.org/10.5281/zenodo.18591948>

Ochsner, C., Pampel H., Höfting J. & Rothfritz L. (2025). Scholarly blogs: An analysis of infrastructural aspects based on German scholarly blogs. *Journal of Documentation*, *81* (7), 520–544. <https://doi.org/10.1108/JD-02-2025-0053>

Ochsner, C., Pampel, H., Höfting, J. & Rothfritz, L. (2025). Wissenschaftsblogs in Deutschland: Eine Analyse infrastruktureller Aspekte. *Bibliothek Forschung und Praxis*. <https://doi.org/10.1515/bfp-2025-0028> (

## Anderer wissenschaftlicher Output

Ochsner, C., & Pampel, H. (2026, March 30). *Ensuring the Long-Term Accessibility of Scholarly Blogs: Bloggers’ Attitudes and Practices*. Zenodo. iConference 2026, Edinburgh, Scotland. <https://doi.org/10.5281/zenodo.19607536>

Ochsner, C., & Pampel, H. (2026, March 17). *Langzeitverfügbarkeit und Nachnutzung von Wissenschaftsblogs: Ergebnisse aus dem Projekt Infra Wiss Blogs*. Social Media Access Days (SMAD), Frankfurt am Main, Germany. <https://doi.org/10.5281/zenodo.19126549>

Ochsner, C., & Pampel, H. (2026, February 25). *Eine Analyse infrastruktureller Aspekte deutscher Wissenschaftsblogs*. Zenodo. DHd 2026: Not Only Text, Not Only Data, Vienna, Austria. <https://doi.org/10.5281/zenodo.18780427>

Ochsner, C., & Pampel, H. (2026, February 9). Virtuelle
Diskussionsveranstaltung: Anforderungen an eine kooperative
Informationsinfrastruktur für die langfristige Verfügbarkeit von
Wissenschaftsblogs. Zenodo. <https://doi.org/10.5281/zenodo.18537453>

Ochsner, C., Pampel, H., Höfting, J., & Rothfritz, L. (2025). *German Scholarly Blogs and their Attributes* \[Data set\]. Zenodo. <https://zenodo.org/records/14905628>

Ochsner, C., & Pampel, H. (2025, September 18). *Wissenschaftsblogs als nachhaltiges Diamond Open Access Publikationsmedium—Herausforderungen und Perspektiven*. Open-Access-Tage 2025, Konstanz, Germany. <https://doi.org/10.5281/zenodo.17171081>

Ochsner, C., Pampel, H., Gebert, B., Seltmann, M., & Wuttke, U. (2025, September 17). *Wissenschaftsblogs als integraler Bestandteil der Open-Access-Landschaft*. Open-Access-Tage 2025, Konstanz, Germany. <https://doi.org/10.5281/zenodo.17171105>

Ochsner, C., Pampel, H., & Höfting, J. (2025, June 25). *Kartierung deutscher Wissenschaftsblogs—Ergebnisse und Impulse*. 113. BiblioCon in Bremen 2025; 9. Bibliothekskongress, Bremen. <https://nbn-resolving.org/urn:nbn:de:0290-opus4-197236>

Ochsner, C., Di Rosa, E., Fenner, M.,
Ködel, S., Pampel, H., Woldering, B., Stadtbäumer, T., Voigt, C., &
Höfting, J. (2025, June 26). *Bibliotheken als betreibende und bewahrende Institutionen für wissenschaftliche Blogs*. 113. BiblioCon in Bremen 2025; 9. Bibliothekskongress, Bremen. <https://opus4.kobv.de/opus4-bib-info/frontdoor/index/index/docId/19469>

Dalkilic, E., Fenner, M., König, M., Ochsner, C., Pampel, H., & Stockhausen, U. (2024, September 20). Workshop 13: Blogs als Blaupause für das wissenschaftsgeleitete Open-Access-Publizieren. Open Access Tage 2024 (OAT2024), Köln. Zenodo. <https://doi.org/10.5281/zenodo.13819866>

Ochsner, C. (2024, Juli 23). Infra Wiss Blogs: Projektvorstellung. 10. Seminar des Instituts für Bibliotheks- und Informationswissenschaft, Humbldt-Unversität zu Berlin, Institut für Bibliotheks- und Informationswissenschaft. Zenodo. <https://doi.org/10.5281/zenodo.12799719>

Pampel, H., & Rothfritz, L. (2024). Kooperative Informationsinfrastruktur für wissenschaftliche Blogs (Infra Wiss Blogs). Zenodo. <https://doi.org/10.5281/zenodo.13234482>
